name: update dependencies

on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - uses: RyanModDev/quilted-dependabot@v0
      - uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'chore(deps): update libraries'
          committer: ''
          branch: quilted-dependabot
          title: 'Update libraries'
          body: ''
